# LuckyDrop by TeamGamerVN

# Placeholders:
# - %player% Tên người chơi
# - %block% Tên block

# Có Broadcast tin nhắn nếu người chơi đào được block hay không?
Broadcast: true
BroadcastMsg: "&eNgười chơi %player% vừa đào được %block% may mắn và nhận được Item thưởng"

# Play âm thanh toàn thế giới hay không?
# Danh sách âm thanh: https://helpch.at/docs/1.8/org/bukkit/Sound.html
PlayGlobalSound: true
GlobalSound: CLICK

# Play âm thanh cho người đào được block?
PlaySingleSound: true
SingleSound: FIREWORK_LAUNCH

# ID Texture
Head:
  Value: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGEwOTcwN2RiNTE0MTk4ZThhZGE1MWRhZTk4NmZiNjYxYmJmMGJiMDk5YThlNDNkZTY2NDQxZmY2Y2JjM2QyYiJ9fX0=" # Head Value
  Name: "&6&lHộp bí ẩn"
  Lore:
    - "&6Cái gì bên trong nhỉ? Mình có dự cảm đéo lành."
    - " "
    - "&7Cầm trên tay và chuột phải để sử dụng"

Commands:
  THOR: # Tên. Đặt cái gì cũng được, này dễ đọc để config sau này thôi.
    message: "" # Thông báo cho người sử dụng. Để trống nếu không dùng.
    broadcast: "&6%player% mở Hộp bí ẩn và bị sét đánh. :(" # Thông báo toàn thế giới. Để trống nếu không dùng.
    sound: "" # Play âm thanh toàn thế giới. Để trống nếu không dùng.
              # Vì trong game sét đánh có sẵn âm thanh rồi, còn lớn vloz nên khỏi dùng.
    commands: # Lệnh. Không có /. Chạy dưới quyền console. Lệnh thực hiện tuần tự.
      - "thor %player%"
  HEAL:
    message: "&6Bạn nhận thấy mình trên Fountain Valley, một quầng sáng màu hồng hiện ra. &c<3"
             # Vì dùng lệnh /heal nên sẽ có dòng chữ mặc định "Bạn được hồi máu" trong game gửi đến người chơi
    broadcast: ""
    sound: "FIREWORK_LAUNCH"
    commands:
      - "effect %player% clear" # Dọn sạch hiệu ứng người chơi đang dính (Gồm cả hiệu ứng có lợi)
      - "heal %player%" # Lệnh của Essentials

Block:
  STONE: # Item sẽ rơi
    Chance: 5 #Tỉ lệ
    RemoveBaseItem: true # Loại bỏ Item từ block gốc hay không, ví dụ ở đây là có chặn drop Stone hay không