main: vn.teamgamervn.Main
name: LuckyDrop
version: 1.0.0
authors: [TeamGamerVN, VinhGaming]
commands:
  luckydrop:
    description: Main command
    aliases: ld

permissions:
  ld.*:
    default: op
    description: Nothing
    children:
      ld.admin: true
      cd.*: true
      cd.admin: true